webserver:
  port: 10180
  host: "0.0.0.0"
  access-log:
    format: "%h %u %t %r %s %b %{Referer}i %T"

k8s:
  namespace: dapla-spark
  volume-name: notebooks
  pod-prefix: jupyter-execution
  mount-path: /notebooks
  container:
    memory-limit: "1024Mi"
    memory-request: "512Mi"
    image: "eu.gcr.io/prod-bip/ssb/dapla/dapla-jupyterlab:master-35989879b39e8fdf06e971c29f2de7678c1180cc"

blueprint:
  url: http://localhost:10170/api/v1

health:
  readiness:
    idle-timeout: 2000



tracing:
  enabled: true
  service: blueprint-execution
  sampler-type: const
  sampler-param: 1
  propagation: b3
  protocol: http
  host: localhost
  port: 14268
  path: /api/traces
  paths:
    - path: "/favicon.ico"
      enabled: false
    - path: "/metrics"
      enabled: false
    - path: "/metrics/vendor"
      enabled: false
    - path: "/metrics/base"
      enabled: false
    - path: "/metrics/application"
      enabled: false
    - path: "/health"
      enabled: false
    - path: "/health/live"
      enabled: false
    - path: "/health/ready"
      enabled: false
