apiVersion: "batch/v1"
kind: "Job"
metadata:
  namespace: {{getNamespace}}
  labels:
    label1: "execute_notebook_dag"
spec:
  template:
    spec:
      containers:
        - name: {{pod-prefix}}
          image: {{container.image}}
          command: [ "papermill", "{{mount-path}}/notebook.ipynb", "{{mount-path}}/result.ipynb", "-k", "pyspark_k8s" ]
          resources:
            limits:
              memory: {{container.memory-limit}}
            requests:
              memory: {{container.memory-request}}
          volumeMounts:
            - name: {{volume-name}}
              mountPath: {{mount-path}}
      restartPolicy: Never
      initContainers:
        - name: "copy-notebooks"
          image: {{container.image}}
          command: [ "curl", "-X", "GET", "{{fetchUrl}}",
                     "-H", "accept: application/x-ipynb+json",
                     "-o", "{{mount-path}}/notebook.ipynb" ]
          volumeMounts:
            - name: {{volume-name}}
              mountPath: {{mount-path}}
      volumes:
        - name: {{volume-name}}
          emptyDir: { }
